import { jsPDF } from "jspdf";
import type { FaceMetrics, FaceShape } from "@/types/face";
import type { QuestionnaireAnswers } from "@/types/questionnaire";
import type { ScoredHaircut } from "@/types/haircut";

interface BarberSpecInput {
  faceShape: FaceShape | null;
  faceMetrics: FaceMetrics | null;
  answers: QuestionnaireAnswers;
  selectedCuts: ScoredHaircut[];
  previewImages?: Record<string, string>;
}

export function generateBarberSpec(input: BarberSpecInput) {
  const { faceShape, faceMetrics, answers, selectedCuts, previewImages } = input;
  const doc = new jsPDF();
  let y = 20;

  // Title
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Matsnap - Barber Tech Spec", 20, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated ${new Date().toLocaleDateString()}`, 20, y);
  doc.setTextColor(0, 0, 0);
  y += 16;

  // Face Profile Section (only if face scan data exists)
  if (faceShape && faceMetrics) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Face Profile", 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const profile = [
      ["Face Shape", faceShape.charAt(0).toUpperCase() + faceShape.slice(1)],
      ["Length/Width Ratio", faceMetrics.faceLengthToWidthRatio.toFixed(2)],
      ["Jaw/Cheekbone Ratio", faceMetrics.jawToCheekboneRatio.toFixed(2)],
      ["Forehead/Cheekbone Ratio", faceMetrics.foreheadToCheekboneRatio.toFixed(2)],
    ];

    for (const [label, value] of profile) {
      doc.setFont("helvetica", "bold");
      doc.text(`${label}:`, 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(value, 85, y);
      y += 7;
    }

    y += 8;
  }

  // Hair Profile Section
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Hair Profile", 20, y);
  y += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const hairProfile = [
    ["Hair Type", answers.hairType.replace("_", " ")],
    ["Thinning", answers.thinning],
    ["Maintenance Pref", `${answers.maintenanceLevel}/5`],
    ["Style Vibes", answers.vibePreferences.join(", ")],
  ];

  for (const [label, value] of hairProfile) {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, 85, y);
    y += 7;
  }

  y += 10;

  // Selected Haircuts
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Recommended Haircuts", 20, y);
  y += 10;

  for (let i = 0; i < selectedCuts.length; i++) {
    const cut = selectedCuts[i];

    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(`${i + 1}. ${cut.haircut.name}`, 20, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    // Description
    const descLines = doc.splitTextToSize(cut.haircut.description, 170);
    doc.text(descLines, 20, y);
    y += descLines.length * 5 + 3;

    // Why it works
    if (cut.explanation) {
      doc.setFont("helvetica", "italic");
      const whyLines = doc.splitTextToSize(`Why: ${cut.explanation}`, 170);
      doc.text(whyLines, 20, y);
      y += whyLines.length * 5 + 3;
    }

    // AI Preview image
    const preview = previewImages?.[cut.haircut.id];
    if (preview) {
      if (y > 180) {
        doc.addPage();
        y = 20;
      }
      try {
        doc.addImage(preview, "PNG", 20, y, 60, 60);
        doc.setFontSize(8);
        doc.setTextColor(120, 120, 120);
        doc.text("AI-generated preview", 22, y + 64);
        doc.setTextColor(0, 0, 0);
        y += 70;
      } catch {
        // Skip if image fails to embed
      }
    }

    // Tags
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(
      `Maintenance: ${cut.haircut.maintenanceLevel}/5 | Vibes: ${cut.haircut.vibeTags.join(", ")}`,
      20,
      y
    );
    doc.setTextColor(0, 0, 0);
    y += 12;
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Matsnap - matsnap.com", 20, y);

  doc.save("matsnap-barber-spec.pdf");
}
